---
- hosts: agora-prod
  vars_files:
    - files/vars.yml
  tasks:
    - name: Install nginx
      apt: pkg=nginx state=installed
    - name: Install certificates for https
      copy: src={{ item }} dest=/etc/nginx/ mode=0600
      with_fileglob:
        - files/server*
      notify:
        - restart nginx
    - name: Deploy nginx configuration for agora
      template: src=templates/agora.vhost.tpl dest=/etc/nginx/sites-available/default
      notify:
        - restart nginx
    - name: Add nodejs user
      user: name={{ agora_user }} state=present
    - name: Clones the Agora repository
      git: repo={{ agora_repo }} dest={{ agora_home }} force=yes
      sudo: yes
      sudo_user: "{{ agora_user }}"
      notify:
        - restart agora
    - name: Install nvm
      sudo: yes
      sudo_user: "{{ agora_user }}"
      git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version={{ nvm_version }}
    - name: Export NVM_DIR for the agora user
      sudo: yes
      sudo_user: "{{ agora_user }}"
      lineinfile: >
        dest=~/.profile
        line="export NVM_DIR=/home/nodejs-prod/.nvm"
    - name: Source nvm in ~/.profile for the agora user
      sudo: yes
      sudo_user: "{{ agora_user }}"
      lineinfile: >
        dest=~/.profile
        line=". ~/.nvm/nvm.sh"
    - name: Install node for the agora user
      command: sudo -iu {{ agora_user }} nvm install {{ node_version }}
    - name: Install Agora upstart script
      template: src=templates/agora.conf.tpl dest=/etc/init/agora.conf
    - name: Deploy agora local configuration
      template: src=templates/local.json.tpl dest={{ agora_home }}/backend/config/local.json
      sudo: yes
      sudo_user: "{{ agora_user }}"
      notify: 
        - restart agora
    - name: Install certificates for agora
      copy: src={{ item }} dest={{ agora_home }}/backend/config/ssl/ owner={{ agora_user }} mode=0600
      with_fileglob:
        - files/server*
        - files/saml*
    - name: Fix hardcoded configuration for discojuice
      replace: "dest={{ agora_home }}/public/login/login-controller.js regexp='https://127.0.0.1:8081' replace='{{ agora_base_url }}'"
    - name: Create logs directory
      file: "path={{ agora_home }}/backend/logs state=directory"
      sudo: yes
      sudo_user: "{{ agora_user }}"
    - name: Install Node dependencies
      command: npm install chdir={{ agora_home }}
      sudo: yes
      sudo_user: "{{ agora_user }}"
    - name: Start Agora cap_net_bind_service
      service: name=agora state=started
    - name: Insert Google Analytis Tracking ID
      lineinfile: dest={{ agora_home }}/public/index.html regexp="^(.*ga\('create', ').*(', 'auto'\);.*)$" line="\1{{ ga_tracking_id }}\2" backrefs=yes
  handlers:
    - name: restart agora
      service: name=agora state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
